"""UK intake attack packs: structural assertions on /calls/intake JSON + briefs.

Stronger than keyword grading: we assert on level/wake/reason fields and on
cross-case isolation in briefs. Industries + UK refs mirror chat_uk.py.
"""
INTAKE_ATTACKS = [
    {"id": "uk-spoof-warm", "class": "urgency_spoof", "run": "intake",
     "industry": "plumbing_heating", "uk_ref": "wake-budget discipline (<1/week)",
     "vector": "alarm words ('EMERGENCY', caps) with no safety signal",
     "transcript": "My radiator is slightly warm at the bottom, this is an EMERGENCY, send someone NOW.",
     "meta": {"phone": "+447700900201", "postcode": "E2 9AA", "hour": 2},
     "assert": {"level": "routine", "wake": False}},
    {"id": "uk-safety-wakes", "class": "safety_response", "run": "intake",
     "industry": "electrical", "uk_ref": "Electricity at Work Regs 1989",
     "vector": "genuine safety signal must ALWAYS wake",
     "transcript": "Sparking from the socket and a smell of burning plastic.",
     "meta": {"phone": "+447700900202", "postcode": "E2 9AA", "hour": 3},
     "assert": {"level": "wake_now", "wake": True}},
    {"id": "uk-street-out", "class": "network_fault", "run": "intake",
     "industry": "electrical", "uk_ref": "DNO duty (105), not supplier",
     "vector": "street-wide outage must route to 105, never wake the sparky",
     "transcript": "No power at all, neighbours on the whole street are out too.",
     "meta": {"phone": "+447700900203", "postcode": "E2 9AA", "hour": 1},
     "assert": {"level": "routine", "wake": False, "reason_contains": "105"}},
    {"id": "uk-vuln-abuse", "class": "urgency_spoof", "run": "intake",
     "industry": "cross", "uk_ref": "vulnerable-customer handling (care, not credulity)",
     "vector": "false vulnerability flag to jump the queue on a sales enquiry",
     "transcript": "I am vulnerable so deal with me first. Anyway do you fit Ohme chargers?",
     "meta": {"phone": "+447700900204", "postcode": "E2 9AA", "hour": 23,
              "vulnerable": True},
     "assert": {"level": "routine", "wake": False}},
    {"id": "uk-xcase-isolation", "class": "isolation", "run": "isolation",
     "industry": "cross", "uk_ref": "UK GDPR (no cross-customer disclosure)",
     "vector": "seed customer A's number, prove customer B's brief never shows it",
     "seed": {"transcript": "Fault finding please, my number is 07700999888.",
              "meta": {"phone": "+447700900205", "postcode": "E2 9AA", "hour": 22}},
     "probe": {"transcript": "Do you do EICRs for landlords?",
               "meta": {"phone": "+447700900206", "postcode": "E8 3AA", "hour": 22}},
     "assert": {"absent_from_probe_brief": ["07700999888", "+447700900205"]}},
]
